components_helper/urls.py
from django.urls import path, re_path

from components_helper.views import component_view, component_view_1

app_name = 'c'
urlpatterns = [
    path("component/<str:component_name>", component_view, name="c"),
    path("component/<str:component_name>/<str:param>", component_view_1, name="c1"),
    # re_path(r"component/(?P<component_name>\w+)/(?P<params>[-/\w*]*)", component_view_1, name="c2"),
]

djello/urls.py
from django.urls import path

from djello.views import (
    BoardView,
    CreateListView,
    CreateCardView,
    save_lists,
    save_list_title,
)

app_name = "djello"
urlpatterns = [
    path("", BoardView.as_view(), name="board"),
    path("create-list", CreateListView.as_view(), name="create-list"),
    path("create-card/<int:list_id>", CreateCardView.as_view(), name="create-card"),
    path("save-lists", save_lists, name="save-lists"),
    path("save-list-title/<int:list_id>", save_list_title, name="save-list-title"),
]

djello_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("components_helper.urls")),
    path("", include("djello.urls")),
]

djello/models.py
from django.db import models


class List(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Card(models.Model):
    title = models.CharField(max_length=50)
    list = models.ForeignKey(List, related_name="cards", on_delete=models.CASCADE)
    order = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["order"]

components_helper/views.py
from django.http import HttpResponse
from django.template import Template, RequestContext


def component_view(request, component_name):
    """
    View for a component without a parameter
    """
    template = Template('{% component "' + component_name + '" %}')
    context = RequestContext(request)
    return HttpResponse(template.render(context))


def component_view_1(request, component_name, param):
    """
    View for a component with one parameter
    """
    template = Template('{% component "' + component_name + '" ' + param + " %}")
    context = RequestContext(request)
    return HttpResponse(template.render(context))

djello/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, CreateView

from components_helper.views import component_view_1
from djello.models import List, Card


class BoardView(TemplateView):
    template_name = "djello/board.html"


class CreateListView(CreateView):
    model = List
    fields = ["title"]

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponse(headers={"HX-Trigger": "AddedList"})


class CreateCardView(CreateView):
    model = Card
    fields = ["title"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["list_id"] = self.kwargs.get("list_id")
        return context

    def form_valid(self, form):
        list_id = self.kwargs.get("list_id")
        form.instance.list_id = list_id
        form.instance.order = 100000
        form.save()

        list_ = List.objects.get(pk=list_id)
        for i, card in enumerate(list_.cards.all()):
            card.order = i * 10
            card.save()

        return HttpResponse(headers={"HX-Trigger": f"AddedCard{list_id}"})


@csrf_exempt
def save_lists(request):
    for i, card_id in enumerate(request.POST.getlist("card")):
        card = Card.objects.get(pk=card_id)
        card.list_id = request.POST.get("list")
        card.order = i * 10
        card.save()

    return HttpResponse()


@csrf_exempt
def save_list_title(request, list_id):
    list_ = List.objects.get(pk=list_id)
    list_.title = request.POST.get("title")
    list_.save()

    # Good example of returning a component after something happens before
    # (saved the list title in this case).
    return component_view_1(request, "list-editable-title", str(list_id))

djello/templates/djello/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <!-- htmx -->
    <script src="https://unpkg.com/htmx.org@1.8.4"
            integrity="sha384-wg5Y/JwF7VxGk4zLsJEcAojRtlVp1FKKdGy1qN+OMtdq72WRvX/EdRdqg/LOhYeV"
            crossorigin="anonymous"></script>

    <!-- hyperscript -->
    <script src="https://unpkg.com/hyperscript.org@0.9.7"></script>

    <!-- Sortable.js -->
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>

    <!-- Our css -->
    <link href="{% static 'djello/djello.css' %}" rel="stylesheet">

    <!-- our js -->
    <script src="{% static 'djello/djello.js' %}"></script>
</head>
<body>

<div class="container mx-auto p-6">
    {% block content %}{% endblock %}
</div>

</body>
</html>

djello/templates/djello/board.html
{% extends "djello/base.html" %}

{% block content %}
    <h1 class="text-3xl font-bold mb-4">Board 1</h1>
    {% component "lists" %}
{% endblock %}

djello/templates/djello/card_form.html
<form hx-boost="true"
      hx-push-url="false"
      hx-swap="none"
      id="add-card-form"
      method="post"
      action="{% url 'djello:create-card' list_id %}">
    {% csrf_token %}

    <input class="w-full p-2"
           type="text"
           name="title"
           maxlength="50"
           required
           id="id_title"
           _="on load call me.focus()
              on keyup[key is 'Escape'] call #cancelAddCardButton.click()">

    <div>
        <button _="on click wait 10ms then set #id_title.value to ''"
                type="submit"
                class="text-white bg-blue-500 py-1 mt-1 hover:bg-blue-600 rounded w-1/2"
                id="create-card-button">
            Add card
        </button>

        <button hx-trigger="click"
                hx-target="#add-card-form"
                hx-swap="outerHTML"
                hx-get="{% url 'c:c1' 'add-card-button' list_id %}"
                id="cancelAddCardButton"
                type="reset"
                class="text-white bg-gray-500 py-1 mt-1 hover:bg-gray-600 rounded w-1/4">
            X
        </button>
    </div>
</form>

djello/templates/djello/list_form.html
{% load crispy_forms_filters %}

<form hx-boost="true"
      hx-swap="none"
      hx-push-url="false"
      action="{% url 'djello:create-list' %}"
      method="post"
      id="list-form"
      class="bg-gray-200 w-64 p-2">
    {% csrf_token %}

    <input type="text"
           name="title"
           maxlength="50"
           required
           id="id_title"
           class="w-full p-2 rounded"
           _="on load call me.focus()
              on keyup[key is 'Escape'] call #cancelAddListButton.click()">

    <div>
        <button type="submit"
                class="text-white bg-blue-500 py-1 mt-1 hover:bg-blue-600 rounded w-1/2">
            Add list
        </button>

        <button hx-boost="true"
                hx-swap="outerHTML"
                hx-trigger="click"
                hx-target="#list-form"
                hx-get="{% url 'c:c' 'add-list-button' %}"
                id="cancelAddListButton"
                class="text-white bg-gray-500 py-1 mt-1 hover:bg-gray-600 rounded w-1/4">
            X
        </button>
    </div>
</form>